const ARTISTS = [
  { id: 'bts', name: 'BTS', type: 'group' },
  { id: 'iu', name: '아이유', type: 'solo' },
  { id: 'kimsejeong', name: '김세정', type: 'solo' },
  { id: 'sunmi', name: '선미', type: 'solo' },
  { id: 'chuu', name: '츄', type: 'solo' },
  { id: 'xnghan', name: 'XngHan&Xoul', type: 'solo' },
  { id: 'yuju', name: '유주', type: 'solo' },
  { id: 'hyolyn', name: '효린', type: 'solo' },
  { id: 'boa', name: 'BoA', type: 'solo' },
  { id: 'bibi', name: '비비', type: 'solo' },
  { id: 'jennie', name: '제니', type: 'solo' },
  { id: 'rose', name: '로제', type: 'solo' },
  { id: 'taemin', name: '태민', type: 'solo' },
  { id: 'kwoneunbi', name: '권은비', type: 'solo' },
  { id: 'kimjunsu', name: '김준수', type: 'solo' },
  { id: 'sondongpyo', name: '손동표', type: 'solo' },
  { id: 'baekhyun', name: '백현', type: 'solo' },
  { id: 'kyuhyun', name: '규현', type: 'solo' },
  { id: 'blackpink', name: 'BLACKPINK', type: 'group' },
  { id: 'nct127', name: 'NCT127', type: 'group' },
  { id: 'seventeen', name: 'SEVENTEEN', type: 'group' },
  { id: 'newjeans', name: 'NewJeans', type: 'group' },
  { id: 'nctdream', name: 'NCT Dream', type: 'group' },
  { id: 'txt', name: 'TXT', type: 'group' },
  { id: 'twice', name: 'TWICE', type: 'group' },
  { id: 'redvelvet', name: 'Red Velvet', type: 'group' },
  { id: 'aespa', name: 'aespa', type: 'group' },
  { id: 'lesserafim', name: 'LE SSERAFIM', type: 'group' },
  { id: 'ive', name: 'IVE', type: 'group' },
  { id: 'itzy', name: 'ITZY', type: 'group' },
  { id: 'enhypen', name: 'ENHYPEN', type: 'group' },
  { id: 'andteam', name: '&TEAM', type: 'group' },
  { id: 'exo', name: 'EXO', type: 'group' },
  { id: 'got7', name: 'GOT7', type: 'group' },
  { id: 'treasure', name: 'TREASURE', type: 'group' },
  { id: 'straykids', name: 'Stray Kids', type: 'group' },
  { id: 'wayv', name: 'Way V', type: 'group' },
  { id: 'snsd', name: '소녀시대', type: 'group' },
  { id: 'nctwish', name: 'NCT WISH', type: 'group' },
  { id: 'riize', name: 'RIIZE', type: 'group' },
  { id: 'babymonster', name: 'BABYMONSTER', type: 'group' },
  { id: 'katseye', name: 'KATSEYE', type: 'group' },
  { id: 'h2h', name: 'Hearts2Hearts', type: 'group' },
  { id: 'winner', name: 'WINNER', type: 'group' },
  { id: 'boynextdoor', name: 'BOYNEXTDOOR', type: 'group' },
  { id: 'tws', name: 'TWS', type: 'group' },
  { id: 'cortis', name: 'CORTIS', type: 'group' }, // 그룹으로 임의 가정
  { id: 'stayc', name: 'STAYC', type: 'group' },
  { id: 'drippin', name: 'DRIPPIN', type: 'group' },
  { id: 'fiftyfifty', name: 'FIFTY FIFTY', type: 'group' },
  { id: 'p1harmony', name: 'P1Harmony', type: 'group' },
  { id: 'tempest', name: 'TEMPEST', type: 'group' },
  { id: 'illit', name: 'ILLIT', type: 'group' },
  { id: 'shinee', name: 'SHINEE', type: 'group' },
  { id: 'billlie', name: 'Billlie', type: 'group' },
  { id: 'pentagon', name: 'PENTAGON', type: 'group' },
  { id: 'apink', name: 'Apink', type: 'group' },
  { id: 'b1a4', name: 'B1A4', type: 'group' },
  { id: 'unis', name: 'UNIS', type: 'group' },
  { id: 'tvxq', name: 'TVXQ!', type: 'group' },
  { id: 'cnblue', name: 'CNBLUE', type: 'group' },
  { id: 'akmu', name: 'AKMU', type: 'group' },
  { id: 'lightsum', name: 'LIGHTSUM', type: 'group' },
  { id: 'idle', name: 'i-dle(아이들)', type: 'group' },
  { id: 'verivery', name: 'VERIVERY', type: 'group' },
  { id: 'fromis9', name: 'fromis_9', type: 'group' },
  { id: 'oneus', name: 'ONEUS', type: 'group' },
  { id: 'purplekiss', name: 'PURPLE KISS', type: 'group' },
  { id: 'btob', name: 'BTOB', type: 'group' },
];

export default ARTISTS;
