export interface Artist {
  id: string;
  name: string;
  type: 'group' | 'solo';
  aliases?: string[]; // Optional aliases field
}

const ARTISTS: Artist[] = [
  { id: 'bts', name: 'BTS', type: 'group', aliases: ['방탄소년단'] },
  { id: 'iu', name: '아이유', type: 'solo', aliases: ['IU'] },
  { id: 'kimsejeong', name: '김세정', type: 'solo', aliases: ['Kim Sejeong'] },
  { id: 'sunmi', name: '선미', type: 'solo', aliases: ['Sunmi'] },
  { id: 'chuu', name: '츄', type: 'solo', aliases: ['CHUU'] },
  { id: 'xnghan', name: 'XngHan&Xoul', type: 'solo' },
  { id: 'yuju', name: '유주', type: 'solo', aliases: ['YUJU'] },
  { id: 'hyolyn', name: '효린', type: 'solo', aliases: ['Hyolyn'] },
  { id: 'boa', name: 'BoA', type: 'solo', aliases: ['보아'] },
  { id: 'bibi', name: '비비', type: 'solo', aliases: ['BIBI'] },
  { id: 'jennie', name: '제니', type: 'solo', aliases: ['JENNIE'] },
  { id: 'rose', name: '로제', type: 'solo', aliases: ['ROSÉ'] },
  { id: 'taemin', name: '태민', type: 'solo', aliases: ['TAEMIN'] },
  { id: 'kwoneunbi', name: '권은비', type: 'solo', aliases: ['Kwon Eunbi'] },
  { id: 'kimjunsu', name: '김준수', type: 'solo', aliases: ['Kim Junsu'] },
  { id: 'sondongpyo', name: '손동표', type: 'solo', aliases: ['Son Dongpyo'] },
  { id: 'baekhyun', name: '백현', type: 'solo', aliases: ['BAEKHYUN'] },
  { id: 'kyuhyun', name: '규현', type: 'solo', aliases: ['KYUHYUN'] },
  { id: 'blackpink', name: 'BLACKPINK', type: 'group', aliases: ['블랙핑크'] },
  { id: 'nct127', name: 'NCT127', type: 'group', aliases: ['엔시티127'] },
  { id: 'seventeen', name: 'SEVENTEEN', type: 'group', aliases: ['세븐틴'] },
  { id: 'newjeans', name: 'NewJeans', type: 'group', aliases: ['뉴진스'] },
  { id: 'nctdream', name: 'NCT_Dream', type: 'group', aliases: ['엔시티드림'] },
  { id: 'txt', name: 'TXT', type: 'group', aliases: ['투모로우바이투게더'] },
  { id: 'twice', name: 'TWICE', type: 'group', aliases: ['트와이스'] },
  { id: 'redvelvet', name: 'RedVelvet', type: 'group', aliases: ['레드벨벳'] },
  { id: 'aespa', name: 'aespa', type: 'group', aliases: ['에스파'] },
  { id: 'lesserafim', name: 'LE SSERAFIM', type: 'group', aliases: ['르세라핌'] },
  { id: 'ive', name: 'IVE', type: 'group', aliases: ['아이브'] },
  { id: 'itzy', name: 'ITZY', type: 'group', aliases: ['있지'] },
  { id: 'enhypen', name: 'ENHYPEN', type: 'group', aliases: ['엔하이픈'] },
  { id: 'andteam', name: '&TEAM', type: 'group', aliases: ['앤팀'] },
  { id: 'exo', name: 'EXO', type: 'group', aliases: ['엑소'] },
  { id: 'got7', name: 'GOT7', type: 'group', aliases: ['갓세븐'] },
  { id: 'treasure', name: 'TREASURE', type: 'group', aliases: ['트레저'] },
  { id: 'straykids', name: 'Stray_Kids', type: 'group', aliases: ['스트레이키즈'] },
  { id: 'wayv', name: 'Way_V', type: 'group', aliases: ['웨이션브이'] },
  { id: 'snsd', name: '소녀시대', type: 'group', aliases: ['Girls\' Generation'] },
  { id: 'nctwish', name: 'NCT_WISH', type: 'group', aliases: ['엔시티위시'] },
  { id: 'riize', name: 'RIIZE', type: 'group', aliases: ['라이즈'] },
  { id: 'babymonster', name: 'BABYMONSTER', type: 'group', aliases: ['베이비몬스터'] },
  { id: 'katseye', name: 'KATSEYE', type: 'group', aliases: ['캣츠아이'] },
  { id: 'h2h', name: 'Hearts2Hearts', type: 'group',aliases: ['하츠투하츠'] },
  { id: 'winner', name: 'WINNER', type: 'group', aliases: ['위너'] },
  { id: 'boynextdoor', name: 'BOYNEXTDOOR', type: 'group', aliases: ['보이넥스트도어'] },
  { id: 'tws', name: 'TWS', type: 'group', aliases: ['투어스'] },
  { id: 'cortis', name: 'CORTIS', type: 'group', aliases: ['코르티스'] },
  { id: 'stayc', name: 'STAYC', type: 'group', aliases: ['스테이씨'] },
  { id: 'drippin', name: 'DRIPPIN', type: 'group', aliases: ['드리핀'] },
  { id: 'fiftyfifty', name: 'FIFTY FIFTY', type: 'group', aliases: ['피프티피프티'] },
  { id: 'p1harmony', name: 'P1Harmony', type: 'group', aliases: ['피원하모니'] },
  { id: 'tempest', name: 'TEMPEST', type: 'group', aliases: ['템페스트'] },
  { id: 'illit', name: 'ILLIT', type: 'group', aliases: ['아일릿'] },
  { id: 'shinee', name: 'SHINEEE', type: 'group', aliases: ['샤이니'] },
  { id: 'billlie', name: 'Billlie', type: 'group', aliases: ['빌리'] },
  { id: 'pentagon', name: 'PENTAGON', type: 'group', aliases: ['펜타곤'] },
  { id: 'apink', name: 'Apink', type: 'group', aliases: ['에이핑크'] },
  { id: 'b1a4', name: 'B1A4', type: 'group', aliases: ['비원에이포'] },
  { id: 'unis', name: 'UNIS', type: 'group', aliases: ['유니스'] },
  { id: 'tvxq', name: 'TVXQ!', type: 'group', aliases: ['동방신기'] },
  { id: 'cnblue', name: 'CNBLUE', type: 'group', aliases: ['씨엔블루'] },
  { id: 'akmu', name: 'AKMU', type: 'group', aliases: ['악뮤', '악동뮤지션'] },
  { id: 'lightsum', name: 'LIGHTSUM', type: 'group', aliases: ['라잇썸'] },
  { id: 'idle', name: 'i-dle', type: 'group', aliases: ['여자아이들'] },
  { id: 'verivery', name: 'VERIVERY', type: 'group', aliases: ['베리베리'] },
  { id: 'fromis9', name: 'fromis_9', type: 'group', aliases: ['프로미스나인'] },
  { id: 'oneus', name: 'ONEUS', type: 'group', aliases: ['원어스'] },
  { id: 'purplekiss', name: 'PURPLE KISS', type: 'group', aliases: ['퍼플키스'] },
  { id: 'btob', name: 'BTOB', type: 'group', aliases: ['비투비'] },
  { id: 'plave', name: 'PLAVE', type: 'group', aliases: ['플레이브'] },
  { id: 'triples', name: 'tripleS', type: 'group', aliases: ['트리플에스'] },
];

export default ARTISTS;
